DATABRICKS_CLUSTER_ID="0721-132926-7xmg1s5j"
DATABRICKS_TOKEN="dapi9d2425f191ced4829a69eb941463fe0c-2"
DATABRICKS_HOST="https://adb-360063509637705.5.azuredatabricks.net"
DATABRICKS_HTTP_PATH = "/sql/1.0/warehouses/b275cf0c491fe3e0"
CLAUDE_ENDPOINT_URL = "https://adb-360063509637705.5.azuredatabricks.net/serving-endpoints/databricks-claude-3-7-sonnet/invocations"
CLAUDE_BEARER_TOKEN = "dapiad3a75a18a34c1dd3e92f7853bad6b15-2"
